<div class="licence">
<span>Licence CC BY-NC-ND</span>
<span>Valérie Roy</span>
<span><img src="../media/ensmp-25-alpha.png"/></span>
</div>

In [5]:
import numpy as np

# multi-dimensional arrays

   - for now we have only created **flat** arrays like **vectors**
   - **but** with *numpy* you can create **multi-dimensional** arrays like **matrices**
   

   - for **multi-dimensional** arrays the underlying memory space is **still** a one-dimensional segment
   - **but** it is viewed as a **multi-dimensional array**  

## accessing the shape of an array
   - with the function *numpy.ndarray.shape*

In [6]:
# we initialize a numpy.ndarray with a flat structure
a = np.array([1, 2, 3, 4, 5, 6], np.int32)
a

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [8]:
# we can see that its shape is one-dimentional array (a vector)
a.shape

(6,)

## creation of multi-dimensional arrays
   - with the *function* *numpy.array*

we create a *2 x 3* matrix
   - by *initializing* the array with a **list of lists**
   - we give the two **rows** of the matrix

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(a)

[[1 2 3]
 [4 5 6]]


its shape is *2 x 3* (two *rows*, 3 *columns*)

In [12]:
a.shape

(2, 3)

## methods to create arrays in *numpy* 

| methods                    | what they do                           	|
|---------------------------|-------------------------------------------|
| *numpy.array*  	| create an array                           |
| *numpy.empty*  	| return an empty without initializing its elements |
| *numpy.zeros*  	| return an array filled with *0.* (float)  |
| *numpy.ones*  	| return an array filled with *1.* (float)  |
| *numpy.linspace* | floats spaced evenly within on an interval |
| *numpy.arange*   | integers spaced  evenly on an interval   |
| *numpy.random.** | random sampling                           |
| *numpy.logspace* | return numbers spaced evenly on a log scale  |

## creating empty arrays

you have to give the **shape** of the array (with the eponym parameter)

In [14]:
# e is an array of shape 3 lines x 2 columns
e = np.empty(shape=(2, 3))
e

array([[4.67811902e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

the array has been created **without initializing the memory**

In [15]:
e[0]

array([4.67811902e-310, 0.00000000e+000, 0.00000000e+000])

   - **without** initialisation but **not** without values !
   - a memory place has **always** a value
   - here you have simply **avoided** the **cost** of initialisation

## creating zeros-initialized arrays

a *(3 x 4)* matrix of 32-bits integers initialized with *1*

In [21]:
np.ones(shape=(3, 4), dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

## creating ones-initialized arrays

a *(4 x 5)* matrix initialized with *1*

In [22]:
z = np.zeros(shape=(4, 5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
z.dtype  

dtype('float64')

## dimensions

a **shape = (n, )** shaped array is **not** a **multi-dimensional** array (it is a **vector**)

In [27]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [28]:
a.shape

(3,)

a **shape = (n, p)** shaped array is a **multi-dimensional** array

In [29]:
b = np.array( [[1, 2, 3]] )
b

array([[1, 2, 3]])

In [30]:
b.shape

(1, 3)

## as many dimensions as you want

we create a structure of:
   - *two* frames of *three* blocks
   - of *four* matrices
   - having *five* rows and *six* columns
   

In [31]:
d = np.ones(shape=(2, 3, 4, 5, 6))
d.shape

(2, 3, 4, 5, 6)

the two lasts are *always* **rows** and **columns**

**very difficult to see on a slide ...**

In [34]:
# np.ones(shape=(2, 3, 4, 2, 2))  # 2 times, 3 blocks, 4 matrices, of size (2 x 2)

## initialising arrays with random numbers
   - lots of functions *numpy.random.randn*, *numpy.random.randint*...  
*2* matrices of *3* rows and *4* columns  
of 8-bits integers **randomly** generated between *1* and *100*

In [39]:
nmin, nmax = 1, 100
np.random.randint(nmin, nmax, size=(2, 3, 4), dtype=np.int8) # nmin included, nmax excluded

array([[[50, 78, 21, 56],
        [34, 22, 72, 33],
        [12, 80, 45,  7]],

       [[14, 71, 81, 69],
        [ 9, 96, 17, 25],
        [42, 64, 30, 19]]], dtype=int8)

### ask for help !

In [40]:
# np.random.randint?

In [41]:
# help(np.random.randint)

In [42]:
# np.random.normal?

In [43]:
# np.random.normal?

# modifing arrays

##  reshaping *numpy.ndarray*
   - with the method *numpy.ndarray.reshape*

In [ ]:
a = np.array([1, 2, 3, 4])
b = a.reshape(2, 2)
b

   - it changes the **shape** of an array (even a multi-dimensional one)
   - by creating a **new view** with a **new indexing**
   - it does not change the **original underlying** array    
   - **resulting** and **original** array share the **same** underlying memory array

### dimension must match
   - the dimension must be a multiple of the number of elements

In [56]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b1 = a.reshape(2, 6)                                  # b1 is a view on a
b2 = b1.reshape(2, 2, 3)                              # b2 is a view on b1
b3 = b2.reshape(1, 1, 3, 4)                           # b3 is a vies on b2

In [57]:
b2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
b3

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]])

## accessing and modifying elements
   - it depends on the **geometry** of the views

In [59]:
a[0] = 99 # we change a:

In [60]:
b1[0][0] # it changes b1

99

In [61]:
b2[0][0][0] # it changes b2

99

In [62]:
b3[0][0][0][0] # it changes b3

99

## flattening an array with *numpy.ravel* 
   - it returns a **view** on the **original data** (when possible)

In [68]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
a_ravel = a.ravel()

   - if we modify **a_ravel**
   - **a** will be modified

In [70]:
a[0][0] = 99; a_ravel[0]

99

## flattening an array with *numpy.ndarray.flatten* 
   - it always returns a **copy** of the **original data**

In [71]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
a_flatten = a.flatten()

   - if we modify **a_flatten**
   - **a** will **not** be modified

In [73]:
a_flatten[2] = 111 ; a[1][0]

3

## iteration on a flattened version of the array 
   - *numpy.ndarray.flat* returns a flat **iterator** over the array

In [74]:
a = np.random.randint(0, 20, 6).reshape(2, 3)
a

array([[ 6, 19,  5],
       [ 8,  0, 18]])

In [76]:
a[1][2] == a.flat[5]

True

### example
   - we get the index of the **minimum**
   - (function *numpy.ndarray.argmin* i.e. argument of the min)
   - we obtain an **index** on the **flat** array
   - we use the **flat iter** to get the element

In [79]:
a.min(), a.argmin()

(0, 4)

In [80]:
a.flat[  a.argmin()  ] == a.min()

True

## resizing an array
   - with the method *ndarray.resize*

   - it change the shape of an array **in-place**
   - i.e. the indexing of the **original array** is **changed**

   - we have the same restriction as for the reshaping
   - the new **dimensions** must **match** the **original ones**

In [89]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a.shape

(12,)

In [90]:
a.resize(2, 2, 3)

In [91]:
# indexes of a are modified
a.shape

(2, 2, 3)

In [92]:
a.resize(2, 6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [94]:
# indexes of a are modified
a.shape

(2, 6)

## repeating elements of an array
   - to create a new one

In [95]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

it **repeat** each element *3* times and return a **flattened** array

In [97]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

## axes of an array

in 2-D: two **axes**:
   - **rows** (indice *0*) and  **columns** (indice *1*)

In [103]:
a = np.random.randint(0, 20, 12).reshape(3, 4)
a

array([[ 3,  2, 18,  4],
       [14,  6,  5, 18],
       [ 0,  7, 16,  2]])

in 3-D, three **axes**:
   - **frames** (indice *0*)
   - **rows** (indice *1*)
   - **columns** (indice *2*

In [104]:
a = np.random.randint(0, 20, 12).reshape(2, 2, 3)
a

array([[[ 3,  3,  9],
        [ 8, 10, 13]],

       [[18,  9, 16],
        [ 6, 16, 11]]])

## repeating along an axis of the array 1/3

In [121]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

**axis 0** we repeat the **rows**

**axis 1** we repeat the **columns**

In [119]:
# repeating each row 2 times
np.repeat(a, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [107]:
# repeating the first column 2 times
#           the second column 3 times
np.repeat(a, (2, 3), axis=1)

array([[1, 1, 2, 2, 2],
       [3, 3, 4, 4, 4]])

## repeating along an axis of the array 2/3

In [122]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(2, 2, 3)
a # we have two matrices of 2 rows and 3 columns

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## repeating along an axis of the array 3/3

In [123]:
# we repeat each frame 2 times
np.repeat(a, 2, axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [124]:
# we repeat first frame 2 times
#           second frame 1 times 
np.repeat(a, (2, 1), axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## tiling an array
   - with the function *numpy.tile* (it returns a **copy**)

In [154]:
a = np.array([1, 2, 3, 4]).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

we tile the array 2 times in column axis

In [159]:
np.tile(a, 2) # there is no axis param.

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

we tile the array 2 times in rows axis

In [163]:
np.tile(a, (2, 1))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

we tile: 2 times in row axis and 3 times in column axis

In [149]:
np.tile(a, (2, 3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

## concatenating arrays
   - the method *numpy.ndarray.concatenate*

   - **returns** a **new** object of type *numpy.ndarray*
   
   - you concatenate along an **axis**

In [164]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])
b = np.array([[10, 20, 30],
              [40, 50, 60]])

In [165]:
np.concatenate((a, b), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

you concatenate along an **axis**, in a 2-dimensional array:
   - rows are **added** on top of each other ($0$ is for **rows**)
   - columns are **added** after each other ($1$ is for **columns**)

In [167]:
np.concatenate((a, b), axis=1)

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

## stacking  python arrays along an axis
   - the function *numpy.stack*
   - **joins** a sequence of **arrays** along an **axis**

In [170]:
a = [0, 2, 3,], [5, 6, 7], [8, 9, 10]

**axis 0**: sub-arrays became rows 

In [171]:
np.stack(a, axis = 0)

array([[ 0,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

**axis 1** : sub-arrays became columns

In [173]:
a = [0, 2, 3,], [5, 6, 7], [8, 9, 10]

In [174]:
np.stack(a, axis = 1)

array([[ 0,  5,  8],
       [ 2,  6,  9],
       [ 3,  7, 10]])

   - see also *np.dstack*, *np.hstack*, *np.vstack*, *numpy.column_stack*

## **concatenation** in higher dimensions (a full example) [1/4]

we create two *numpy.ndarray* *a* and *b*  
each having *2* frames of *3* matrices of *4* rows and *5* columns

In [186]:
a = np.array(np.arange(0, 240, 2)) # even numbers from 0 to 238
a.resize(2, 3, 4, 5)               # 2 groups of 3 matrix of 4 rows and 5 columns

In [187]:
b = np.array(np.arange(1, 241, 2)) # odd numbers from 1 to 249
b.resize(2, 3, 4, 5)               # 2 groups of 3 matrix of 4 rows and 5 columns

### **concatenation** along axis *0* [2/4]
   - we stack the *2* frames, in the frame axis
   - i.e. we obtain *4* frames

In [181]:
c = np.concatenate((a, b), axis=0)
c.shape

(4, 3, 4, 5)

*c[0]* is *a[0]*, *c[1]* is *a[1]*  
*c[2]* is *b[0]*, *c[3]* is *b[1]*  

In [182]:
np.all( c[0] == a[0] )   # we compare arrays we obtain an array of booleans
                         # we check if all elements are true

True

### **concatenation along axis *1* [3/4]
   - axis *1* is the axis of the matrices
   - we stack the *3* matrices, we obtain *6* matrices
      - the three first matrices come from *a* (even numbers)
      - the three other matrices come from *b* (odd numbers)

In [199]:
d = np.concatenate((a, b), axis=1)
print(f'shape {d.shape}')
# d[0][0], d[0][1], d[0][2] are even numbers and d[0][3], d[0][4], d[0][5] odd ones

shape (2, 6, 4, 5)


### **concatenation** of *a* and *b* along axis *2* [4/4]
   - in our example, it **stacks** the rows of the matrices
   - the matrices have *8* rows
      - the first four rows of the matrices come from *a* (even numbers)
      - the other rows come from *b* (odd numbers)  
(same for last **axis** *3*)

In [200]:
d = np.concatenate((a, b), axis=2)
d.shape

(2, 3, 8, 5)

## spliting arrays
   - with the method *numpy.ndarray.split*, you split along the given **axis**

for our examples, we create a matrix *(5 x 6)* of elements between *0* and *30*

In [203]:
a = np.array(np.arange(1, 31)).reshape((5, 6))
a, a.dtype, a.shape

(array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]), dtype('int64'), (5, 6))

### spliting by giving a number *n* of elements

   - it splits along the **axis** in two sub-arrays
   - the first array contains the *n* elements (when possible)
   - the last sub-array contains the elements that remain
   - the last sub-array can be empty

**spliting by giving a number of elements (*3*) along the rows axis**
   - the *(5 x 6)* array is split in two sub-arrays: a *(3 x 6)* and a *(2 x 6)* array

In [210]:
un, deux = np.split(a, [3], axis=0)

In [211]:
un.shape

(3, 6)

In [212]:
deux.shape

(2, 6)

In [213]:
un

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [214]:
deux

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

**spliting by giving a number of elements (*2*) along the column axis**
   - the *(5 x 6)* array is split in two sub-arrays: a *(5 x 2)* and a *(5 x 4)* array

In [215]:
un, deux = np.split(a, [2], axis=1)

In [216]:
un.shape

(5, 2)

In [217]:
deux.shape

(5, 4)

In [218]:
un

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26]])

In [219]:
deux

array([[ 3,  4,  5,  6],
       [ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24],
       [27, 28, 29, 30]])

**spliting when the number of elements exceeds the shape**


exceeding the shape along the **rows** axis:
   - the *(5 x 6)* array is split in two sub-arrays: a *(5 x 6)* and *(0 x 6)*

In [222]:
un, deux = np.split(a, [5], axis=0)

In [223]:
un.shape

(5, 6)

In [226]:
deux.shape # empty !

(0, 6)

exceeding the shape along the **columns** axis:
   - the *(5 x 6)* array is split in two sub-arrays: a *(5 x 6)* and *(0 x 6)*

In [243]:
un, deux = np.split(a, [6], axis=1)

In [244]:
un.shape

(5, 6)

In [245]:
deux.shape

(5, 0)

In [246]:
un

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [247]:
deux # empty

array([], shape=(5, 0), dtype=int64)

In [252]:
un, deux = np.split(a, [99], axis=1)
un.shape, deux.shape

((5, 6), (5, 0))

### *split* giving a section [1/2]
   - you indicate along which **axis** the array must be split
   - and you indicate the sections (list of indices)

split **[p, q]** along **rows** results in:
   - rows from index *0* to *p* (excluded)
   - rows from index *p* to *q* (excluded)
   - rows from index *q* to the end

In [305]:
a.shape

(5, 6)

In [306]:
a1, a2, a3 = np.split(a, [2, 4], axis=0)
a1.shape, a2.shape, a3.shape, 

((2, 6), (2, 6), (1, 6))

In [311]:
# we print all matrices
a = np.array(np.arange(1, 31)).reshape((5, 6))
a1, a2, a3 = np.split(a, [2, 4], axis=0)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [312]:
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [313]:
a2

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [314]:
a3

array([[25, 26, 27, 28, 29, 30]])

split **[p, q]** along **columns**  
columns from index *0* to *p* (excluded)  
columns from index *p* to *q* (excluded)  
columns from index *q* to the end

In [321]:
a.shape

(5, 6)

In [322]:
a1, a2, a3 = np.split(a, [2, 4], axis=1)
a1.shape, a2.shape, a3.shape, 

((5, 2), (5, 2), (5, 2))

In [328]:
# we print all matrices
a = np.array(np.arange(1, 31)).reshape((5, 6))
a1, a2, a3 = np.split(a, [2, 4], axis=1)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [329]:
a1

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26]])

In [330]:
a2

array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22],
       [27, 28]])

In [331]:
a3

array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24],
       [29, 30]])

In [332]:
a1, a2, a3, a4, a5, a6, a7, a8 = np.split(a, [1, 2, 3, 4, 5, 6, 7], axis=0)
a1.shape, a2.shape, a3.shape, a4.shape, a5.shape, a6.shape, a7.shape, a8.shape

((1, 6), (1, 6), (1, 6), (1, 6), (1, 6), (0, 6), (0, 6), (0, 6))

### split in higher dimensions [1/4]

   - we create one array with two frames of one matrix *(5 x 6)*

In [337]:
a = np.array(np.arange(1, 61)).reshape((2, 5, 6))

In [338]:
a[0] # first frame

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [346]:
a[1] # second frame

array([[31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

**spliting along axis 0 (i.e. the frames) [2/4]**

we split the axis 0 (the two frames) in two ([0, 1[ and [1, 2[)

In [347]:
a1, a2 = np.split(a, [1], axis=0)

we obtain two arrays of 1 block, each one with one matrix *(5 x 6)*

In [348]:
a1.shape

(1, 5, 6)

In [349]:
a2.shape

(1, 5, 6)

**split along axis 1 (i.e. the rows) [3/4]**
   - the first block contains the rows [0, 2[ of the matrices
   - the second block contains the rows [2, -1] of the matrices

In [350]:
a1, a2 = np.split(a, [2], axis=1)

In [351]:
a1

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42]]])

In [352]:
a2

array([[[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]],

       [[43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]]])

**split along axis 2 (i.e. columns)[4/4]**

   - the first block contains the columns [0, 3[ of the matrices
   - the second block contains the columns [3, -1] of the matrices

In [353]:
a1, a2 = np.split(a, [3], axis=2)

In [354]:
a1

array([[[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21],
        [25, 26, 27]],

       [[31, 32, 33],
        [37, 38, 39],
        [43, 44, 45],
        [49, 50, 51],
        [55, 56, 57]]])

In [355]:
a2

array([[[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24],
        [28, 29, 30]],

       [[34, 35, 36],
        [40, 41, 42],
        [46, 47, 48],
        [52, 53, 54],
        [58, 59, 60]]])

## deleting rows, columns and elements
   - with the function *numpy.delete*
   - it returns a new array

In [361]:
a = np.arange(0, 12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

deleting a list of **rows** (rows *1* and *0*)

In [362]:
np.delete(a, [1, 0], axis=0)

array([[ 8,  9, 10, 11]])

deleting a list of **columns** (cols. *0* and *3*)

In [363]:
np.delete(a, [0, 3], axis=1)

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

## deleting elements

In [364]:
a = np.arange(0, 12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

deleting a list of **elements**  
in the flattened array

In [365]:
np.delete(a, [0, 6, 11])

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10])

## sorting an array  with the function *numpy.sort*
   - it returns a **copy** of the array
   

In [373]:
a = np.random.randint(0, 10, (3, 4)) # matrix (3 x 4) with randon ints between 0 and 10 excluded
a

array([[8, 0, 6, 3],
       [3, 7, 6, 3],
       [0, 9, 8, 1]])

sorting in the **axis** of the **rows** (the columns ends-up sorted)

In [374]:
np.sort(a, axis=0)

array([[0, 0, 6, 1],
       [3, 7, 6, 3],
       [8, 9, 8, 3]])

sorting in the **axis** of the **columns** (the rows ends-up sorted)

In [377]:
a

array([[8, 0, 6, 3],
       [3, 7, 6, 3],
       [0, 9, 8, 1]])

In [378]:
np.sort(a, axis=1) 

array([[0, 3, 6, 8],
       [3, 3, 6, 7],
       [0, 1, 8, 9]])

## sorting an array  in place
   - with the function *numpy.ndarray.sort*
   - it sorts the array **in place**

In [402]:
a = np.random.randint(0, 8, (2, 4))
a

array([[6, 4, 7, 3],
       [5, 6, 3, 6]])

In [403]:
a.sort(axis=0) # sorting along rows
a        # the columns ends-up sorted

array([[5, 4, 3, 3],
       [6, 6, 7, 6]])

In [404]:
a = np.random.randint(0, 8, (2, 4))
a

array([[7, 3, 0, 3],
       [1, 1, 7, 2]])

In [405]:
a.sort(axis=1) # sorting along cols
a        # the rows ends-up sorted

array([[0, 3, 3, 7],
       [1, 1, 2, 7]])