<div class="licence">
<span>Licence CC BY-NC-ND</span>
<span>Valérie Roy</span>
<span><img src="../media/ensmp-25-alpha.png" /></span>
</div>

In [2]:
import numpy as np

# Broadcasting is useful when we work with arrays of different sizes

## reminder about the dimensions

**dimension 2**: *shape=(r, c)* is a matrix with *r* **rows** and *c* **columns**
   
   
**dimension 3**: *shape=(p, r, c)* is *p* matrices with *r* **rows** and *c* **columns**
   
   
**greater dimension**: *shape=(g1, ..., gn, r, c)* the two last are *r* **rows**, and *c* **columns**

## operations on matrices of the same shape
operations are done on an **element-by-element** basis:
   - the matrices must have **the same shape**

In [6]:
a = np.arange(0, 10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
b = np.arange(10, 20).reshape(2, 5)
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
a * b # element-by-element product

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

##  operation when matrices have different *but consistent* sizes
   - *numpy* **relaxes** the constraint i.e. the matrices can have **different shapes**
   - **but** the **shapes** must meet **certain conditions**

example

In [19]:
a = np.arange(0, 4)
print(f'a={a}')
b = np.array([10])
print(f'b={b}')

a=[0 1 2 3]
b=[10]


In [20]:
a + b

array([10, 11, 12, 13])

to **add** [0, 1, 2, 3] and [10]
   - [10] is **expended** to **match the size** of *a*
   - *b* became [10, 10, 10, 10]

## broadcasting **rules**

   - when arrays **do not have** the **same** shape
   - *numpy* **expands** the arrays (*when possible*)
   - for an **element-by-element** operation to **take place**

## rules:   
   
   - dimensions are **compared** from **right** to **left**
   - *columns*, then *rows*, then *frames*, ...
   
   
   - dimensions are taken **pairwise**
   - broadcasting is **possible**
      1. when the **dimensions** are **identical**
      1. when **one** is $1$
      
      
   
   - https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
   - http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc

## example when sizes are consistent

In [29]:
a = 100 * np.ones((2, 3))
print('a =', a)
print()

b = 4
print('b =', b)
print()

print('a + b =', a + b)

a = [[100. 100. 100.]
 [100. 100. 100.]]

b = 4

a + b = [[104. 104. 104.]
 [104. 104. 104.]]


the **shape** of $a$ is $(2_a, 3_a)$  
the **shape** of $b$ is $(1_b)$  

$3_a$ is **compared** to $1_b$  
$b$ **became** $[4, 4, 4]$ (1 row, size $3$)     
the **shape** of $b$ is **now** $(1_b, 3_b)$  

$2_a$ is **compared** to $1_b$  
$b$ **became** $[[4, 4, 4], [4, 4, 4]]$ (2 rows)  
the **shape** of $b$ is **now** $(2_b, 3_b)$  

**a** and **b** can **now** be added

## example when sizes are not consistant

In [33]:
a = 100 * np.ones((2, 3))
print(a)

print()

b = 10 * np.ones((2, 4))
print(b)

try:
    a + b
except ValueError as e:
    print(e)

[[100. 100. 100.]
 [100. 100. 100.]]

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]]
operands could not be broadcast together with shapes (2,3) (2,4) 


the **shape** of $a$ is $(2_a, 3_a)$  
the **shape** of $b$ is $(2_b, 4_b)$
   
**broadcasting** compares **pairs** $(3_a, 4_b)$  

$3_a$ is **compared** to $4_b$  
**no rule** can be applied !!
   
shapes **cannot** be **broadcast**

the operation **does not follow the rules** $\Rightarrow$ **it fails** (raising a ValueError)

## a more complex example

In [42]:
a = 9 * np.ones((1, 3))
print(f'a = {a}')
print()

b = 100 * np.ones((2, 1))
print(f'b = {b}')

print()
print(f'a+b = {a + b}')

a = [[9. 9. 9.]]

b = [[100.]
 [100.]]

a+b = [[109. 109. 109.]
 [109. 109. 109.]]


the **shape** of $a$ is $(1_a, 3_a)$  
the **shape** of $b$ is $(2_b, 1_b)$
      
**broadcasting** compares $3_a$ and $1_b$  
$b$ is broadcast to **fit** $3$ **columns**  
[[100., 100., 100.],  
 [100., 100., 100.],]

broadcasting compare $(1_a, 2_b)$   
$a$ is broadcast to **fit** $2$ **rows**  
[[9., 9., 9.],  
 [9., 9., 9.],] ok **now** for a+b

## Broadcasting and vectorization
   - broadcasting is **very efficient**
   - the broadcast elements are **not actually created in memory**
   - broadcasting is based on **optimized C code**
   - it has the **same efficiency** as **vectorized** operations